# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge

